[features]
seeds = false
skip-lint = false
[programs.localnet]
carrot_loyalty_alpha = "5jtwmP1bNjvEAu23qerh2WCzpULsqZJuGX5cFATbZBHS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/san/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
